### ISSUE TITLE
eaf-file-manager 无法打开

### ISSUE THREAD

**Issue by miire** [emacs-eaf/emacs-application-framework#1036]
**Describe the bug**
eaf-file-manager 打开之后空白，什么东西都没有，无法使用。

**To Reproduce**
`emacs -q`:
```
(add-to-list 'load-path "~/.emacs.d/lisp/packages/emacs-application-framework/")
(require 'eaf)

(require 'eaf-music-player)
(require 'eaf-browser)
(require 'eaf-terminal)
(require 'eaf-markdown-previewer)
(require 'eaf-rss-reader)
(require 'eaf-vue-demo)
(require 'eaf-camera)
(require 'eaf-pdf-viewer)
(require 'eaf-file-sender)
(require 'eaf-video-player)
(require 'eaf-file-browser)
(require 'eaf-airshare)
(require 'eaf-org-previewer)
(require 'eaf-jupyter)
(require 'eaf-system-monitor)
(require 'eaf-2048)
(require 'eaf-git)
(require 'eaf-file-manager)
(require 'eaf-mindmap)
(require 'eaf-netease-cloud-music)
(require 'eaf-demo)
(require 'eaf-image-viewer)
```
执行命令：
`eval-buffer`
`eaf-open-file-manager `

**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM: 
   - Arch Linux x86_64 
   - Xfce 4.16
 - Versions of Dependencies: Python 3.10.8
 - M-x emacs-version: 28.2

**Error logs**
```
Traceback (most recent call last):
  File "/home/miire/.emacs.d/lisp/packages/emacs-application-framework/core/utils.py", line 51, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/miire/.emacs.d/lisp/packages/emacs-application-framework/eaf.py", line 153, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/miire/.emacs.d/lisp/packages/emacs-application-framework/eaf.py", line 171, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
  File "/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/buffer.py", line 72, in __init__
    self.load_index_html(__file__)
  File "/home/miire/.emacs.d/lisp/packages/emacs-application-framework/core/webengine.py", line 1507, in load_index_html
    with open(self.index_file, "r") as f:
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/dist/index.html'
```

**Screenshots**

**Additional context**

**Comment by MatthewZMD** [comment]
The dependencies probably wasn't installed correctly. Please run `install-eaf.py --install file-manager --force`

**Comment by miire** [comment]
> 

I'm run`install-eaf.py --install file-manager --force`. It still doesn't work.

log:
```
[EAF] Installing python dependencies
[EAF] Running pip3 install --user -U pypinyin pygments exif @ /home/miire/.emacs.d/lisp/packages/emacs-application-framework
Requirement already satisfied: pypinyin in /home/miire/.local/lib/python3.10/site-packages (0.47.1)
Requirement already satisfied: pygments in /usr/lib/python3.10/site-packages (2.13.0)
Requirement already satisfied: exif in /home/miire/.local/lib/python3.10/site-packages (1.3.5)
Collecting exif
  Downloading exif-1.4.0-py3-none-any.whl (30 kB)
Requirement already satisfied: plum-py<2.0.0,>=0.5.0 in /home/miire/.local/lib/python3.10/site-packages (from exif) (0.8.5)
Installing collected packages: exif
  Attempting uninstall: exif
    Found existing installation: exif 1.3.5
    Uninstalling exif-1.3.5:
      Successfully uninstalled exif-1.3.5
Successfully installed exif-1.4.0
[EAF] WARN: removing /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules
[EAF] Running npm install --force @ /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager
npm WARN using --force Recommended protections disabled.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

added 1477 packages, and audited 1478 packages in 23s

117 packages are looking for funding
  run `npm fund` for details

23 vulnerabilities (1 moderate, 17 high, 5 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[EAF] Running npm run build @ /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager

> vue-demo@0.1.0 build
> vue-cli-service build

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

⠸  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
⠇  Building for production...Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
⠸  Building for production.../home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:114
			throw e;
			^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/cache-loader/dist/index.js:147:7
    at /home/miire/.emacs.d/lisp/packages/emacs-application-framework/app/file-manager/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

```

**Comment by MatthewZMD** [comment]
Yes, as you can see from the log that the npm install failed.

This is a dependency issue and it is out of the scope of EAF.

**Comment by MatthewZMD** [comment]
Try something like this:
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

Or google the error yourself.

**Comment by Jousimies** [comment]
同样的问题，npm 装完后没有 dist 这个文件夹，

**Comment by manateelazycat** [comment]
> 同样的问题，npm 装完后没有 dist 这个文件夹，

需要 npm build, 而且mac现在可以直接用 install-eaf.py 自动化处理这些问题

**Comment by Jousimies** [comment]
执行过下面的命令
`./install-eaf.py --install file-manager --force`结果显示如下
```
[EAF] Updating file-manager to newest version...
[EAF] Running git branch @ app/file-manager
[EAF] Running git symbolic-ref HEAD @ app/file-manager
[EAF] Running git pull origin master @ app/file-manager
From https://github.com/emacs-eaf/eaf-file-manager
 * branch            master     -> FETCH_HEAD
Already up to date.

[EAF] Installing dependencies for the selected applications
[EAF] Installing python dependencies
[EAF] Running pip3 install --user -U pypinyin pygments exif @ /Users/jousimies/.emacs.d/emacs-application-framework
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pypinyin in /Users/jousimies/Library/Python/3.10/lib/python/site-packages (0.47.1)
Requirement already satisfied: pygments in /Users/jousimies/Library/Python/3.10/lib/python/site-packages (2.13.0)
Requirement already satisfied: exif in /Users/jousimies/Library/Python/3.10/lib/python/site-packages (1.4.0)
Requirement already satisfied: plum-py<2.0.0,>=0.5.0 in /Users/jousimies/Library/Python/3.10/lib/python/site-packages (from exif) (0.8.5)
[EAF] WARN: removing /Users/jousimies/.emacs.d/emacs-application-framework/app/file-manager/node_modules
[EAF] Running npm install --force @ /Users/jousimies/.emacs.d/emacs-application-framework/app/file-manager
npm WARN using --force Recommended protections disabled.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

added 1480 packages, and audited 1481 packages in 22s

117 packages are looking for funding
  run `npm fund` for details

24 vulnerabilities (1 low, 1 moderate, 17 high, 5 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[EAF] Running npm run build @ /Users/jousimies/.emacs.d/emacs-application-framework/app/file-manager

> vue-demo@0.1.0 build
> export NODE_OPTIONS=--openssl-legacy-provider ; vue-cli-service build

node: --openssl-legacy-provider is not allowed in NODE_OPTIONS

[EAF] Please always ensure the following are added to your init.el:
(require 'eaf-pdf-viewer)
(require 'eaf-browser)
(require 'eaf-file-manager)
(require 'eaf-system-monitor)

[EAF] The following applications failed to install:
/Users/jousimies/.emacs.d/emacs-application-framework/app/file-manager
[EAF] Please rerun ./install-eaf.py with `--force`, or install them manually!
[EAF] ------------------------------------------
[EAF] install-eaf.py finished.
```
上面的结果npm 安装看起来是没有问题，网络也没问题。

也执行过 `npm rebuild`显示rebuilt dependencies successfully。

file-manager 文件夹中还是没有 dist 这个文件夹。
