### ISSUE TITLE
Cannot launch eaf web browser even though I installed Qt6

### ISSUE THREAD

**Issue by afidegnum** [emacs-eaf/emacs-application-framework#1037]
**Describe the bug**
I have the following error while installing eaf on WSL2/debian

Traceback (most recent call last):
  File "/home/afidegnum/.emacs.d/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa
ImportError: libQt6Core.so.6: cannot open shared object file: No such file or directory

Process *eaf* exited abnormally with code 1
Traceback (most recent call last):
  File "/home/afidegnum/.emacs.d/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa
ImportError: libQt6Core.so.6: cannot open shared object file: No such file or directory

Process *eaf* exited abnormally with code 1

**To Reproduce**
This happens when i tried opening a Qt web browser

**Expected behavior**
I was expecting to have the browser openned

**Versions (please complete the following info):**
 - Distro and DE/WM: WSL2 / Debian bullseye
Qt 6.4.2
 - M-x emacs-version: GNU Emacs 28.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2022-10-26

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.

**Screenshots**
Traceback (most recent call last):
  File "/home/afidegnum/.emacs.d/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa
ImportError: libQt6Core.so.6: cannot open shared object file: No such file or directory

Process *eaf* exited abnormally with code 1
Traceback (most recent call last):
  File "/home/afidegnum/.emacs.d/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa
ImportError: libQt6Core.so.6: cannot open shared object file: No such file or directory

Process *eaf* exited abnormally with code 1

**Additional context**

**Comment by afidegnum** [comment]
I'm using debian bullseye, `apt-file` command didn't work out, neither `apt-cache search libQt6Core.so.6`

**Comment by arstum** [comment]
Arch system can't find out libQt6Core.so.6

**Comment by afidegnum** [comment]
@arstum I'm using Debian bullseye

**Comment by manateelazycat** [comment]
> Arch system can't find out libQt6Core.so.6
![截图 2022-12-02 15-33-18](https://user-images.githubusercontent.com/237487/205239696-7c1f7f4f-8800-43a0-b3de-e75f22cb598b.png)

**Comment by manateelazycat** [comment]
> I'm using debian bullseye, `apt-file` command didn't work out, neither `apt-cache search libQt6Core.so.6`

You need install apt-file first, then use apt-file search search package that include libQt6Core.so.6.

In arch, is qt6-base provide libQtCore.so.6

**Comment by afidegnum** [comment]
This is what I have done so far. 

```
$  sudo apt-file search libQt6Core.so.6
libqt6core6: /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
libqt6core6: /usr/lib/x86_64-linux-gnu/libQt6Core.so.6.3.1
$  sudo apt-install libqt6core6
sudo: apt-install: command not found
$  sudo apt install libqt6core6
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libqt6core6 is already the newest version (6.3.1+dfsg-9~bpo11+2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```
