### ISSUE TITLE
Eaf just kicks to a blank buffer

### ISSUE THREAD

**Issue by theswordsgame** [emacs-eaf/emacs-application-framework#1068]
**Describe the bug**
when i try to go to google in eaf browser it kicks to blank buffer with a "no braveblock found" error message

**To Reproduce**
copy the end of my init.el file
(add-to-list 'load-path "~/.emacs.d/site-lisp/emacs-application-framework/")
(require 'eaf)
(require 'eaf-browser)
(require 'eaf-pdf-viewer)

**Expected behavior**
eaf browser opens with google

**Versions (please complete the following info):**
 - Fedora 37, Gnome:
 - Latest version of dependencies:
 - emacs 28.2, doomemacs latest:

**Error logs**
ModuleNotFoundError: No module named 'braveblock'
Traceback (most recent call last):
  File "/home/theswordsgame/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 52, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/theswordsgame/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 155, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/theswordsgame/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 170, in create_buffer
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/theswordsgame/.emacs.d/site-lisp/emacs-application-framework/app/browser/buffer.py", line 32, in <module>
    import braveblock
ModuleNotFoundError: No module named 'braveblock'

**Screenshots**
[Screencast from 2023-02-27 16-51-10.webm](https://user-images.githubusercontent.com/72705300/221709203-f4131cc0-536f-4aee-a163-e2b7323ca072.webm)

**Comment by manateelazycat** [comment]
pip3 install braveblock

**Comment by theswordsgame** [comment]
it became worse now nothing shows and i cant open the eaf buffer to show the errors
![Screenshot from 2023-02-27 17-41-07](https://user-images.githubusercontent.com/72705300/221714428-447827ac-4a29-49bc-adf9-e4544ecfa29e.png)
![Screenshot from 2023-02-27 17-42-23](https://user-images.githubusercontent.com/72705300/221714539-75174af3-cbe9-4737-8ad7-7cb120bc76a2.png)

**Comment by manateelazycat** [comment]
please use xwayland，wayland have problem with newest gnome
