### ISSUE TITLE
windows下打开office文件错误

### ISSUE THREAD

**Issue by simpleboy95** [emacs-eaf/emacs-application-framework#1105]
使用eaf打开doc或者xls文件时报错
Traceback (most recent call last):
  File "c:\Emacs\.emacs.d\site-lisp\emacs-application-framework\core\utils.py", line 52, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "c:\Emacs\.emacs.d\site-lisp\emacs-application-framework\eaf.py", line 155, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "c:\Emacs\.emacs.d\site-lisp\emacs-application-framework\eaf.py", line 168, in create_buffer
    spec = importlib.util.spec_from_file_location("AppBuffer", module_path) # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 802, in spec_from_file_location
TypeError: expected str, bytes or os.PathLike object, not list
大佬您看一下这个好解决吗，我知道eaf主要是在Linux下用，但是要是能在windows下打开office文件办公会方便很多，麻烦大佬看看

**Comment by manateelazycat** [comment]
这个要安装 libreoffice 才行， 我不知道 windows 能不能装 libreoffice

**Comment by manateelazycat** [comment]
本质就是通过 libreoffice 转换 word 到 pdf, 再用 eaf-pdf-viewer 打开。

https://github.com/emacs-eaf/eaf-pdf-viewer/blob/c59b1df6bfddb4859013a26b6619c24699b3f0ff/eaf-pdf-viewer.el#L568

你看看能否装 libreoffice， 或者看看 Windows 平台有没有方便转换 word 为 pdf 的方法， 欢迎提交补丁。

我不用Windows快20年了， 没法帮助你。

**Comment by simpleboy95** [comment]
谢谢大佬
