### ISSUE TITLE
必须用eaf-open-office打开doc才能正常打开，用C-x C-f打开会报错

### ISSUE THREAD

**Issue by simpleboy95** [emacs-eaf/emacs-application-framework#1112]
**Describe the bug**
用eaf-oepn-office打开doc文件可以正常打开，但是用C-x C-f打开会报错。
已经在.emacs中添加配置
(defun adviser-find-file (orig-fn file &rest args)
  (let ((fn (if (commandp 'eaf-open) 'eaf-open orig-fn)))
    (pcase (file-name-extension file)
      ("pdf"  (apply fn file nil))
      ("epub" (apply fn file nil))
      ("doc" (apply fn file nil))
      ("docx" (apply fn file nil))
      (_      (apply orig-fn file args)))))
(advice-add #'find-file :around #'adviser-find-file)
buffer eaf 中报错如下：
Traceback (most recent call last):
  File "/home/lqs_is_a_goodboy/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 56, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/lqs_is_a_goodboy/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 155, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/lqs_is_a_goodboy/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 168, in create_buffer
    spec = importlib.util.spec_from_file_location("AppBuffer", module_path) # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 802, in spec_from_file_location
TypeError: expected str, bytes or os.PathLike object, not list

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework/blob/b06ec816c69ac576236474b73ae013da201a2a60/eaf.el#L1919 已经支持了， 请去掉你自己自定义的  adviser-find-file
