### ISSUE TITLE
`RuntimeError: PyQt6.QtWebEngineCore cannot import type 'QModelRoleDataSpan' from PyQt6.QtCore` after install

### ISSUE THREAD

**Issue by Thysrael** [emacs-eaf/emacs-application-framework#1128]
**Describe the bug**
After I following README to install eaf, I try to run `eaf-open-demo` or `eaf-open`, eaf didn't work.

**To Reproduce**
Yes I git clone the newest update of eaf. And I run the install_eaf.py successfully(I guess, because nothing wrong happend).
I use `emacs -Q` and eval the code below:

```lisp
(add-to-list 'load-path "~/.emacs.d/site-lisp/emacs-application-framework/")
(require 'eaf)

(require 'eaf-browser)
(require 'eaf-pdf-viewer)
(require 'eaf-demo)
```

**Expected behavior**
I hope eaf can work correctly.

**Versions (please complete the following info):**
 - Distro and DE/WM:
 here is my `screenfetch`

```

 ██████████████████  ████████     thysrael@thysrael-82av
 ██████████████████  ████████     OS: Manjaro 23.1.0 Vulcan
 ██████████████████  ████████     Kernel: x86_64 Linux 6.1.62-1-MANJARO
 ██████████████████  ████████     Uptime: 1d 1h 6m
 ████████            ████████     Packages: 2233
 ████████  ████████  ████████     Shell: bash
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: KDE 5.112.0 / Plasma 5.27.9
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breeze [GTK2/3]
 ████████  ████████  ████████     Icon Theme: breeze
 ████████  ████████  ████████     Disk: 360G / 1.3T (29%)
 ████████  ████████  ████████     CPU: Intel Core i7-10750H @ 12x 2.6GHz [43.0°C]
 ████████  ████████  ████████     GPU: NVIDIA GeForce GTX 1650 Ti
                                  RAM: 5879MiB / 15904MiB
```
 - Versions of Dependencies: I'm so sorry I didn't get it, I just run the install_eaf.py
 - M-x emacs-version:
```
GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8)
```
**Error logs**
```
Traceback (most recent call last):
  File "/home/thysrael/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PyQt6.QtWebEngineCore cannot import type 'QModelRoleDataSpan' from PyQt6.QtCore

Process *eaf* exited abnormally with code 1
Traceback (most recent call last):
  File "/home/thysrael/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt6 import QtWebEngineWidgets as NeverUsed # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PyQt6.QtWebEngineCore cannot import type 'QModelRoleDataSpan' from PyQt6.QtCore
```

**Screenshots**
![image](https://github.com/emacs-eaf/emacs-application-framework/assets/72613958/8a01b512-e719-49d8-8e18-d74e0963d2c6)

**Comment by manateelazycat** [comment]
Looks your Qt or PyQt not install complete in your system.

**Comment by Thysrael** [comment]
> Looks your Qt or PyQt not install complete in your system.

Thank you, it fixed. 

I remove the `pyqt6` installed from `pacman`, and create a new python venv at `eaf` directory. It works well.
