### ISSUE TITLE
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)

### ISSUE THREAD

**Issue by Cipivious** [emacs-eaf/emacs-application-framework#1150]
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
Traceback (most recent call last):
  File "/home/yang/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 56, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/yang/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 156, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/yang/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 174, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/.emacs.d/site-lisp/emacs-application-framework/app/system-monitor/buffer.py", line 37, in __init__
    self.load_index_html(__file__)
  File "/home/yang/.emacs.d/site-lisp/emacs-application-framework/core/webengine.py", line 1603, in load_index_html
    with open(self.index_file, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/yang/.emacs.d/site-lisp/emacs-application-framework/app/system-monitor/dist/index.html'

**Comment by manateelazycat** [comment]
Please follow README, use eaf.py install all dependences , make sure system-monitor do "npm build"
