### ISSUE TITLE
Windows下安装eaf报错

### ISSUE THREAD

**Issue by goodboylqs** [emacs-eaf/emacs-application-framework#1151]
一、bug描述
        大佬之前跟您说过一回，就是在windows下执行./install-eaf.py的时候报错（报错内容在面下），当时您修好了，是这个链接 （https://github.com/emacs-eaf/emacs-application-framework/issues/1130）  指向的issue修复的 。
        可是这次同样的问题又出现了，我不太懂产生bug的原因，issue1130里面您说的是“等 setuptool 修复以后， 再解除 sexpdata 版本限制”
二、报错内容

> Collecting PyQt6==6.5.0
>   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/28/01/9e4b91cb0c1023934b1dc654c5bbfc29cbabcbf6092f936b74aee46dd637/PyQt6-6.5.0.tar.gz (1.0 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... error
>   error: subprocess-exited-with-error
> 
>   × Preparing metadata (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [26 lines of output]
>       pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
>       Traceback (most recent call last):
>         File "/usr/lib/python3.11/sitepackages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/usr/lib/python3.11/sitepackages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/usr/lib/python3.11/sitepackages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
>           whl_basename = backend.build_wheel(metadata_directory, config_settings)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pipbuildenv1p20xxx5/overlay/lib/python3.11/sitepackages/sipbuild/api.py", line 46, in build_wheel
>           project = AbstractProject.bootstrap('wheel',
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pipbuildenvp20xxx5/overlay/lib/python3.11/sitepackages/sipbuild/abstract_project.py", line 92, in bootstrap
>           project.setup(pyproject, tool, tool_description)
>         File"/tmp/pipbuildenv1p20xxx5/overlay/lib/python3.11/sitepackages/sipbuild/project.py", line 587, in setup
>           self.apply_user_defaults(tool)
>         File "/tmp/pipinstalle9ap6di5/pyqt6_09ff25d355784dd6b2ccbdacb64d65f0/project.py", line 66, in apply_user_defaults
>           super().apply_user_defaults(tool)
>         File "/tmp/pipbuildenv1p20xxx5/overlay/lib/python3.11/sitepackages/pyqtbuild/project.py", line 51, in apply_user_defaults
>           super().apply_user_defaults(tool)
>         File "/tmp/pipbuildenv1p20xxx5/overlay/lib/python3.11/sitepackages/sipbuild/project.py", line 237, in apply_user_defaults
>           self.builder.apply_user_defaults(tool)
>         File "/tmp/pipbuildenv1p20xxx5/overlay/lib/python3.11/sitepackages/pyqtbuild/builder.py", line 50, in apply_user_defaults
>           raise PyProjectOptionException('qmake',
>       sipbuild.pyproject.PyProjectOptionException
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

**Comment by MatthewZMD** [comment]
读起来太费劲了，能不能排版一下？

**Comment by goodboylqs** [comment]
> 读起来太费劲了，能不能排版一下？

大佬您看这样行吗，我是小白不太会github您见谅= =
