### ISSUE TITLE
install-eaf.py 无法检测到本地安装的 pip.

### ISSUE THREAD

**Issue by zw963** [emacs-eaf/emacs-application-framework#848]
我是按照官方的教程安装的 pip

1. Download the script, from https://bootstrap.pypa.io/get-pip.py.
2. 运行 python get-pip.py

安装成功后，可以看到 pip 可用。

```sh
 ╰─ $ pip --version
pip 21.2.4 from /home/zw963/.local/lib/python3.9/site-packages/pip (python 3.9)\
 ╰─ $ which pip
/home/zw963/.local/bin/pip

```

尝试 `python install-eaf.py`, 得到如下错误：

```sh
 ╰─ $ python install-eaf.py
[EAF] Running sudo pacman -Sy --noconfirm @ /home/zw963/others/Git/emacs-application-framework
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archlinuxcn is up to date
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running sudo pacman -Sy --noconfirm wmctrl python-pyqt5 python-pyqt5-sip python-pyqtwebengine @ /home/zw963/others/Git/emacs-application-framework
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archlinuxcn is up to date
warning: wmctrl-1.07-6 is up to date -- reinstalling
warning: python-pyqt5-5.15.4-1 is up to date -- reinstalling
warning: python-pyqt5-sip-12.9.0-1 is up to date -- reinstalling
warning: python-pyqt5-webengine-5.15.4-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (4) python-pyqt5-5.15.4-1  python-pyqt5-sip-12.9.0-1  python-pyqt5-webengine-5.15.4-1  wmctrl-1.07-6

Total Installed Size:  27.46 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] 
(4/4) checking keys in keyring                                                  [#############################################] 100%
(4/4) checking package integrity                                                [#############################################] 100%
(4/4) loading package files                                                     [#############################################] 100%
(4/4) checking for file conflicts                                               [#############################################] 100%
(4/4) checking available disk space                                             [#############################################] 100%
:: Processing package changes...
(1/4) reinstalling wmctrl                                                       [#############################################] 100%
(2/4) reinstalling python-pyqt5-sip                                             [#############################################] 100%
(3/4) reinstalling python-pyqt5                                                 [#############################################] 100%
(4/4) reinstalling python-pyqt5-webengine                                       [#############################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[EAF] Running pip install --user epc lxml @ /home/zw963/others/Git/emacs-application-framework
Traceback (most recent call last):
  File "/home/zw963/others/Git/emacs-application-framework/install-eaf.py", line 376, in <module>
    main()
  File "/home/zw963/others/Git/emacs-application-framework/install-eaf.py", line 361, in main
    install_core_deps(distro, deps_dict)
  File "/home/zw963/others/Git/emacs-application-framework/install-eaf.py", line 218, in install_core_deps
    install_py_deps(deps_dict["pip"][sys.platform])
  File "/home/zw963/others/Git/emacs-application-framework/install-eaf.py", line 116, in install_py_deps
    return run_command(command)
  File "/home/zw963/others/Git/emacs-application-framework/install-eaf.py", line 88, in run_command
    process = subprocess.Popen(command, env = english_env, stdin = subprocess.PIPE,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pip'
```

**Comment by manateelazycat** [comment]
为什么不直接用 Arch 的 https://archlinux.org/packages/extra/any/python-pip/ ？

**Comment by zw963** [comment]
> 为什么不直接用 Arch 的 https://archlinux.org/packages/extra/any/python-pip/ ？

因为我不常使用 pip，较少用 python 写东西，因此没有安装这个 system 包。
我明天重启一下电脑，看看能不能好。（安装完后，还没有 logout 过）

**Comment by manateelazycat** [comment]
感觉是环境的问题，如果确定是EAF的问题再重新打开吧。

**Comment by zw963** [comment]
重启还是不行，我电脑上应该没有什么针对 python 的配置，因为 python 不是我的工作、业余语言，所以感觉不应该啊？

我又安装了一次。

```sh
 ╰─ $ python get-pip.py 
Defaulting to user installation because normal site-packages is not writeable
Collecting pip
  Using cached pip-21.2.4-py3-none-any.whl (1.6 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
  WARNING: The scripts pip, pip3 and pip3.9 are installed in '/home/zw963/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
Successfully installed pip-21.2.4
```

我觉得问题可能来自于最后一句：

```
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
```

而我的 $PATH, 正好就是这样使用的。

PATH="~/.local/bin:$PATH"

**Comment by zw963** [comment]
It works after replace as $HOME/.local/bin, thanks
