### ISSUE TITLE
Use eaf-open-... get same error as follow

### ISSUE THREAD

**Issue by ssayno** [emacs-eaf/emacs-application-framework#867]
After using `eamcs -q myeaf.el` we get the error as follow, I install `eaf` by reading this [guideline](https://github.com/emacs-eaf/emacs-application-framework/blob/master/README.zh-CN.md)
```
Traceback (most recent call last):
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 198, in init_epc_client
    epc_client = EPCClient(("localhost", emacs_server_port), log_traceback=True)
  File "/home/sayno/.local/lib/python3.8/site-packages/epc/client.py", line 95, in __init__
    self.connect(socket_or_address)
  File "/home/sayno/.local/lib/python3.8/site-packages/epc/client.py", line 110, in connect
    self.socket = socket.create_connection(socket_or_address)
  File "/opt/anaconda/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/opt/anaconda/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] 拒绝连接
Traceback (most recent call last):
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 562, in <module>
    eaf = EAF(sys.argv[1:])
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 69, in __init__
    eaf_config_dir = get_emacs_config_dir()
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 338, in get_emacs_config_dir
    emacs_config_dir = os.path.join(os.path.expanduser(get_emacs_var("eaf-config-location")), '')
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 325, in get_emacs_var
    (symbol_value, symbol_is_boolean) = epc_client.call_sync("get-emacs-var", [var_name])
AttributeError: 'NoneType' object has no attribute 'call_sync'

Process *eaf* exited abnormally with code 1
Traceback (most recent call last):
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 198, in init_epc_client
    epc_client = EPCClient(("localhost", emacs_server_port), log_traceback=True)
  File "/home/sayno/.local/lib/python3.8/site-packages/epc/client.py", line 95, in __init__
    self.connect(socket_or_address)
  File "/home/sayno/.local/lib/python3.8/site-packages/epc/client.py", line 110, in connect
    self.socket = socket.create_connection(socket_or_address)
  File "/opt/anaconda/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/opt/anaconda/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] 拒绝连接
Traceback (most recent call last):
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 562, in <module>
    eaf = EAF(sys.argv[1:])
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 69, in __init__
    eaf_config_dir = get_emacs_config_dir()
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 338, in get_emacs_config_dir
    emacs_config_dir = os.path.join(os.path.expanduser(get_emacs_var("eaf-config-location")), '')
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 325, in get_emacs_var
    (symbol_value, symbol_is_boolean) = epc_client.call_sync("get-emacs-var", [var_name])
AttributeError: 'NoneType' object has no attribute 'call_sync'

Process *eaf* exited abnormally with code 1
```
So I submit this issue.

**Comment by manateelazycat** [comment]
please don't use anaconda

**Comment by ssayno** [comment]
After uninstall anaconda, the same error after I use `eaf-open-...`

**Comment by ssayno** [comment]
```
Traceback (most recent call last):
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 198, in init_epc_client
    epc_client = EPCClient(("localhost", emacs_server_port), log_traceback=True)
  File "/home/sayno/.local/lib/python3.9/site-packages/epc/client.py", line 95, in __init__
    self.connect(socket_or_address)
  File "/home/sayno/.local/lib/python3.9/site-packages/epc/client.py", line 110, in connect
    self.socket = socket.create_connection(socket_or_address)
  File "/usr/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] 拒绝连接
Traceback (most recent call last):
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 562, in <module>
    eaf = EAF(sys.argv[1:])
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 69, in __init__
    eaf_config_dir = get_emacs_config_dir()
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 338, in get_emacs_config_dir
    emacs_config_dir = os.path.join(os.path.expanduser(get_emacs_var("eaf-config-location")), '')
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 325, in get_emacs_var
    (symbol_value, symbol_is_boolean) = epc_client.call_sync("get-emacs-var", [var_name])
AttributeError: 'NoneType' object has no attribute 'call_sync'

Process *eaf* exited abnormally with code 1
Traceback (most recent call last):
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 198, in init_epc_client
    epc_client = EPCClient(("localhost", emacs_server_port), log_traceback=True)
  File "/home/sayno/.local/lib/python3.9/site-packages/epc/client.py", line 95, in __init__
    self.connect(socket_or_address)
  File "/home/sayno/.local/lib/python3.9/site-packages/epc/client.py", line 110, in connect
    self.socket = socket.create_connection(socket_or_address)
  File "/usr/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] 拒绝连接
Traceback (most recent call last):
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 562, in <module>
    eaf = EAF(sys.argv[1:])
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 69, in __init__
    eaf_config_dir = get_emacs_config_dir()
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 338, in get_emacs_config_dir
    emacs_config_dir = os.path.join(os.path.expanduser(get_emacs_var("eaf-config-location")), '')
  File "/home/sayno/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 325, in get_emacs_var
    (symbol_value, symbol_is_boolean) = epc_client.call_sync("get-emacs-var", [var_name])
AttributeError: 'NoneType' object has no attribute 'call_sync'

Process *eaf* exited abnormally with code 1
```

**Comment by manateelazycat** [comment]
I don't know reason, looks like something wrong in your epc server or network setting.

**Comment by ssayno** [comment]
Add sockt5 for emacs, new `error` appeared, `or: Wrong type argument: eaf-epc-manager, nil`, thanks for your answers.

**Comment by manateelazycat** [comment]
> Add sockt5 for emacs, new `error` appeared, `or: Wrong type argument: eaf-epc-manager, nil`, thanks for your answers.

are you compile emacs yourself? can you install.standard version to test?

**Comment by ssayno** [comment]
Thank, after I install a new Arch, I can use eaf.
