### ISSUE TITLE
TypeError: setZoomFactor(self, float): argument 1 has unexpected type 'str'

### ISSUE THREAD

**Issue by damoncro** [emacs-eaf/emacs-application-framework#878]
**Describe the bug**
Can not use `eaf-open-browser` to browse internet, it always crashes with white screen.

**To Reproduce**
`M-x eaf-open browser`

**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM: MacOS Big Sur x86_64
 - Versions of Dependencies:
 - M-x emacs-version: emacs-mac 27.2, Doom Emacs,

**Error logs**
```
  Deprecation: 'pageCropBox' removed from class 'Document' after v1.19.0 - use 'page_cropbox'.
  Deprecation: 'setCropBox' removed from class 'Page' after v1.19.0 - use 'set_cropbox'.
  Deprecation: 'getText' removed from class 'Page' after v1.19.0 - use 'get_text'.
  Deprecation: 'setRotation' removed from class 'Page' after v1.19.0 - use 'set_rotation'.
  Deprecation: 'getPixmap' removed from class 'Page' after v1.19.0 - use 'get_pixmap'.
  Deprecation: 'invertIRect' removed from class 'Pixmap' after v1.19.0 - use 'invert_irect'.
  Deprecation: 'getImageList' removed from class 'Page' after v1.19.0 - use 'get_images'.
  Deprecation: 'getImageBbox' removed from class 'Page' after v1.19.0 - use 'get_image_bbox'.
  Saved session:  /Users/damonchen/.emacs.d/.local/straight/build-27.2/eaf/app/pdf-viewer/buffer.py /Users/damonchen/OneDrive/Org/Doc/Calibre/Dorling Kindersley/Artist's Drawing Techniques (943)/Artist's Drawing Techniques - Dorling Kindersley.pdf 6836.649999999998:2.3087115405473897:fit_to_width:True:0
  Saved session:  /Users/damonchen/.emacs.d/.local/straight/build-27.2/eaf/app/pdf-viewer/buffer.py /Users/damonchen/OneDrive/Org/Doc/Calibre/David Brody/How to Draw (949)/How to Draw - David Brody.pdf 42826.67931133435:2.887830687830687:fit_to_customize:True:0
  Saved session:  /Users/damonchen/.emacs.d/.local/straight/build-27.2/eaf/app/pdf-viewer/buffer.py /Users/damonchen/OneDrive/Org/Doc/Calibre/Dorling Kindersley/How To Be An Artist (944)/How To Be An Artist - Dorling Kindersley.pdf 4889.491457760118:1.8766468344413056:fit_to_customize:True:0
  Traceback (most recent call last):
    File "/Users/damonchen/.doom.d/modules/eaf/core/utils.py", line 60, in on_signal_received
      self._func(obj, *args, **kwargs)
    File "/Users/damonchen/.emacs.d/.local/straight/build-27.2/eaf/eaf.py", line 170, in new_buffer
      self.create_buffer(buffer_id, url, module_path, arguments)
    File "/Users/damonchen/.emacs.d/.local/straight/build-27.2/eaf/eaf.py", line 187, in create_buffer
      app_buffer = module.AppBuffer(buffer_id, url, arguments)
    File "/Users/damonchen/.emacs.d/.local/straight/build-27.2/eaf/app/browser/buffer.py", line 38, in __init__
      BrowserBuffer.__init__(self, buffer_id, url, arguments, False)
    File "/Users/damonchen/.doom.d/modules/eaf/core/webengine.py", line 813, in __init__
      self.buffer_widget.zoom_reset()
    File "/Users/damonchen/.doom.d/modules/eaf/core/utils.py", line 168, in wrapped_f
      return f(*args, **kwargs)
    File "/Users/damonchen/.doom.d/modules/eaf/core/webengine.py", line 369, in zoom_reset
      self.setZoomFactor(self.default_zoom)
  TypeError: setZoomFactor(self, float): argument 1 has unexpected type 'str'
  
  Process *eaf* abort trap: 6
```

**Screenshots**

![image](https://user-images.githubusercontent.com/92778185/142997689-bd11ae30-1a1d-44d5-9fe1-ee97d64258c4.png)

**Additional context**

**Comment by manateelazycat** [comment]
@damoncro Try update newest version, thanks for report.

**Comment by damoncro** [comment]
Problem still exists:
```
Traceback (most recent call last):
  File "/Users/damonchen/.doom.d/modules/eaf/core/utils.py", line 60, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/damonchen/.emacs.d/.local/straight/build-27.2/eaf/eaf.py", line 170, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/Users/damonchen/.emacs.d/.local/straight/build-27.2/eaf/eaf.py", line 187, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
  File "/Users/damonchen/.emacs.d/.local/straight/build-27.2/eaf/app/browser/buffer.py", line 116, in __init__
    self.reset_default_zoom()
  File "/Users/damonchen/.doom.d/modules/eaf/core/webengine.py", line 1260, in reset_default_zoom
    self.buffer_widget.setZoomFactor(zoom_factor)
TypeError: setZoomFactor(self, float): argument 1 has unexpected type 'str'

Process *eaf* abort trap: 6
Traceback (most recent call last):
  File "/Users/damonchen/.doom.d/modules/eaf/core/utils.py", line 60, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/damonchen/.emacs.d/.local/straight/build-27.2/eaf/eaf.py", line 250, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '61c1-5d12-4ef7-bc91-1653-a5c0-3416'

Process *eaf* abort trap: 6

```

**Comment by manateelazycat** [comment]
try again
