### ISSUE TITLE
Error installing on Manjaro

### ISSUE THREAD

**Issue by MarkoSchuetz** [emacs-eaf/emacs-application-framework#891]
**Describe the bug**
I get an error when trying to install following the steps in the instructions.

**To Reproduce**
➜  emacs-application-framework git:(master) ./install-eaf.py                     
[EAF] Running yay -Sy --noconfirm --needed @ /home/marko/.emacs.d/site-lisp/emacs-application-framework
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running yay -Sy --noconfirm --needed wmctrl python-pyqt5 python-pyqt5-sip python-pyqtwebengine @ /home/marko/.emacs.d/site-lisp/emacs-application-framework
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
warning: wmctrl-1.07-6 is up to date -- skipping
warning: python-pyqt5-5.15.6-2 is up to date -- skipping
warning: python-pyqt5-sip-12.9.0-1 is up to date -- skipping
warning: python-pyqt5-webengine-5.15.5-1 is up to date -- skipping
 there is nothing to do
[EAF] Running pip install --user epc lxml @ /home/marko/.emacs.d/site-lisp/emacs-application-framework
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: epc in /usr/lib/python3.9/site-packages (0.0.5)
Requirement already satisfied: lxml in /usr/lib/python3.9/site-packages (4.6.4)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 454, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 348, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 217, in _attempt_to_pin_criterion
    satisfied = all(
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 218, in <genexpr>
    self._p.is_satisfied_by(requirement=r, candidate=candidate)
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 165, in is_satisfied_by
    return requirement.is_satisfied_by(candidate)
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/requirements.py", line 112, in is_satisfied_by
    return spec.contains(candidate.version, prereleases=True)
  File "/usr/lib/python3.9/site-packages/packaging/specifiers.py", line 790, in contains
    item = parse(item)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 57, in parse
    return Version(version)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 296, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

**Expected behavior**
Installation without error.

**Versions (please complete the following info):**
 - Distro and DE/WM: up-to-date Manjaro, KDE/KWin using Xorg 
 - Versions of Dependencies:
 - M-x emacs-version: 27.2

**Comment by manateelazycat** [comment]
I haven't those lines in your install log:

```
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see pypa/pip#5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
```

Maybe you should check your pip version?

**Comment by manateelazycat** [comment]
I use Manjaro everyday, I believe it's something wrong in your enviroment.

Please re-open issue if you have any clue.
