### ISSUE TITLE
doom下运行失败，似乎python报错了

### ISSUE THREAD

**Issue by quarkquartet** [emacs-eaf/emacs-application-framework#909]
在doom emacs下安装了eaf，使用markdown preview, 打开的窗口是空白的，没有直接报错。
安装步骤：
在doom的`package.el`里，写的是
```emacs-lisp
(when (package! eaf :recipe (:host github
                             :repo "manateelazycat/emacs-application-framework"
                             :files ("*.el" "*.py" "app" "core")
                             :build (:not compile)))

  (package! ctable :recipe (:host github :repo "kiwanami/emacs-ctable"))
  (package! deferred :recipe (:host github :repo "kiwanami/emacs-deferred"))
  (package! epc :recipe (:host github :repo "kiwanami/emacs-epc")))
```
然后`doom sync`。随后去`~/.emacs.d/.local/straight/repos/emacs-application-framework`下跑`install-eaf.py`。
我用的是python3的virtualenv创建的虚拟环境，这一步开头直接报错：
```
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running pip install --user epc pyqt5 pyqt5-sip pyqtwebengine mac-app-frontmost @ /Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```
查了下，virtualenv应该不能用--users. 我手动把`install-eaf.py`的那个`--users`删了。这样安装就成了。完整log是：
```
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running pip install epc pyqt5 pyqt5-sip pyqtwebengine mac-app-frontmost @ /Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework
Requirement already satisfied: epc in /Users/isaac/envs/py386/lib/python3.8/site-packages (0.0.5)
Requirement already satisfied: pyqt5 in /Users/isaac/envs/py386/lib/python3.8/site-packages (5.15.4)
Requirement already satisfied: pyqt5-sip in /Users/isaac/envs/py386/lib/python3.8/site-packages (12.9.0)
Requirement already satisfied: pyqtwebengine in /Users/isaac/envs/py386/lib/python3.8/site-packages (5.15.4)
Requirement already satisfied: mac-app-frontmost in /Users/isaac/envs/py386/lib/python3.8/site-packages (2020.12.3)
Requirement already satisfied: sexpdata>=0.0.3 in /Users/isaac/envs/py386/lib/python3.8/site-packages (from epc) (0.0.3)
Requirement already satisfied: PyQt5-Qt5>=5.15 in /Users/isaac/envs/py386/lib/python3.8/site-packages (from pyqt5) (5.15.2)
Requirement already satisfied: PyQtWebEngine-Qt5>=5.15 in /Users/isaac/envs/py386/lib/python3.8/site-packages (from pyqtwebengine) (5.15.2)
[EAF] Finished installing core dependencies
[EAF] ------------------------------------------
[EAF] ------------------------------------------
[EAF] Installing application dependencies
[EAF] (1/21) airshare. Install? (Y/n): n
[EAF] (2/21) browser. Install? (Y/n): Y
[EAF] (3/21) camera. Install? (Y/n): n
[EAF] (4/21) demo. Install? (Y/n): n
[EAF] (5/21) file-browser. Install? (Y/n): n
[EAF] (6/21) file-manager. Install? (Y/n): n
[EAF] (7/21) file-sender. Install? (Y/n): n
[EAF] (8/21) image-viewer. Install? (Y/n): n
[EAF] (9/21) jupyter. Install? (Y/n): n
[EAF] (10/21) markdown-previewer. Install? (Y/n): Y
[EAF] (11/21) mermaid. Install? (Y/n): n
[EAF] (12/21) mindmap. Install? (Y/n): n
[EAF] (13/21) music-player. Install? (Y/n): n
[EAF] (14/21) org-previewer. Install? (Y/n): Y
[EAF] (15/21) pdf-viewer. Install? (Y/n): Y
[EAF] (16/21) system-monitor. Install? (Y/n): n
[EAF] (17/21) terminal. Install? (Y/n): n
[EAF] (18/21) video-player. Install? (Y/n): n
[EAF] (19/21) vue-demo. Install? (Y/n): n
[EAF] (20/21) netease-cloud-music. Install? (Y/n): n
[EAF] (21/21) rss-reader. Install? (Y/n): n
[EAF] Adding browser application to EAF...
[EAF] Running git clone --depth 1 --single-branch https://github.com/emacs-eaf/eaf-browser.git app/browser @ /Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework
Cloning into 'app/browser'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 17 (delta 0), reused 12 (delta 0), pack-reused 0
Receiving objects: 100% (17/17), 4.72 MiB | 17.57 MiB/s, done.
[EAF] Adding markdown-previewer application to EAF...
[EAF] Running git clone --depth 1 --single-branch https://github.com/emacs-eaf/eaf-markdown-previewer.git app/markdown-previewer @ /Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework
Cloning into 'app/markdown-previewer'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 17 (delta 0), reused 10 (delta 0), pack-reused 0
Receiving objects: 100% (17/17), 1023.49 KiB | 7.21 MiB/s, done.
[EAF] Adding org-previewer application to EAF...
[EAF] Running git clone --depth 1 --single-branch https://github.com/emacs-eaf/eaf-org-previewer.git app/org-previewer @ /Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework
Cloning into 'app/org-previewer'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 14 (delta 0), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (14/14), 19.68 KiB | 1.51 MiB/s, done.
[EAF] Adding pdf-viewer application to EAF...
[EAF] Running git clone --depth 1 --single-branch https://github.com/emacs-eaf/eaf-pdf-viewer.git app/pdf-viewer @ /Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework
Cloning into 'app/pdf-viewer'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 14 (delta 0), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (14/14), 1.93 MiB | 9.97 MiB/s, done.

[EAF] Installing dependencies for installed applications
[EAF] Installing python dependencies
[EAF] Running pip install pysocks pymupdf @ /Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework
Requirement already satisfied: pysocks in /Users/isaac/envs/py386/lib/python3.8/site-packages (1.7.1)
Requirement already satisfied: pymupdf in /Users/isaac/envs/py386/lib/python3.8/site-packages (1.18.19)
[EAF] Running npm install @ /Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/app/browser

added 2 packages, and audited 3 packages in 731ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[EAF] Running npm install @ /Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/app/markdown-previewer

added 246 packages, and audited 247 packages in 3s

12 packages are looking for funding
  run `npm fund` for details

7 vulnerabilities (3 moderate, 4 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
[EAF] Running npm install @ /Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/app/org-previewer

added 1 package, and audited 2 packages in 471ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[EAF] Finished installing applications and their dependencies
[EAF] Please ensure the following are added to your init.el:
(require 'eaf-pdf-viewer)
(require 'eaf-browser)
(require 'eaf-markdown-previewer)
(require 'eaf-org-previewer)
[EAF] Please run both 'git pull' and 'install-eaf.py' (M-x eaf-install-and-update) to update EAF, applications and their dependencies.
[EAF] ------------------------------------------
[EAF] install-eaf.py finished.
```

随后我在doom的`config.el`里写：
```emacs-lisp
(add-to-list 'load-path "~/.emacs.d/.local/straight/repos/emacs-application-framework/")

(use-package! eaf
  :commands (eaf-open-browser eaf-open find-file)
  :config
  (use-package! ctable)
  (use-package! deferred)
  (use-package! epc)
  (require 'eaf-markdown-previewer)
  (require 'eaf-pdf-viewer))
```
重启emacs。运行`eaf-open`，选择一个markdown文件。emacs界面出现左右两个窗口：左边是正常的markdown编辑模式，右边是eaf-open，但内容是空的。
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26316540/149649567-ac2fb2b8-f814-4f8b-a620-b18705ff1fdc.png">
我点开`*eaf*`的buffer，内容是这样：
```
Traceback (most recent call last):
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/utils.py", line 61, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 158, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 175, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/app/markdown-previewer/buffer.py", line 39, in __init__
    BrowserBuffer.__init__(self, buffer_id, url, arguments, False)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/webengine.py", line 741, in __init__
    self.add_widget(BrowserView(buffer_id))
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/webengine.py", line 81, in __init__
    (self.default_zoom, self.show_hover_link, self.marker_letters, self.marker_fontsize) = get_emacs_vars(
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/utils.py", line 340, in get_emacs_vars
    return list(map(lambda result: convert_emacs_bool(result[0], result[1]) if result != [] else False, epc_client.call_sync("get-emacs-vars", args)))
  File "/Users/isaac/envs/py386/lib/python3.8/site-packages/epc/handler.py", line 402, in call_sync
    return self._blocking_request(self.call, timeout, name, args)
  File "/Users/isaac/envs/py386/lib/python3.8/site-packages/epc/handler.py", line 384, in _blocking_request
    return bc.result(timeout=timeout)
  File "/Users/isaac/envs/py386/lib/python3.8/site-packages/epc/handler.py", line 116, in result
    raise reply
epc.handler.ReturnError: [Symbol('void-variable'), Symbol('eaf-browser-default-zoom')]
Traceback (most recent call last):
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/utils.py", line 61, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 238, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: 'e7dc-0a27-1b4f-3e04-43ba-8909-31f1'
Traceback (most recent call last):
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/utils.py", line 61, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 238, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: 'e7dc-0a27-1b4f-3e04-43ba-8909-31f1'
Traceback (most recent call last):
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/utils.py", line 61, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 238, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: 'e7dc-0a27-1b4f-3e04-43ba-8909-31f1'
Traceback (most recent call last):
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/utils.py", line 61, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 238, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: 'e7dc-0a27-1b4f-3e04-43ba-8909-31f1'
Traceback (most recent call last):
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/utils.py", line 61, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 238, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: 'e7dc-0a27-1b4f-3e04-43ba-8909-31f1'
Traceback (most recent call last):
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/utils.py", line 61, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 238, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: 'e7dc-0a27-1b4f-3e04-43ba-8909-31f1'
Traceback (most recent call last):
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/utils.py", line 61, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 238, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: 'e7dc-0a27-1b4f-3e04-43ba-8909-31f1'
```
可否解惑？

**Comment by manateelazycat** [comment]
用git clone下载后执行 install-eaf.py 应该就可以，不要用包管理器。

**Comment by MatthewZMD** [comment]
> ```emacs-lisp
>   (package! ctable :recipe (:host github :repo "kiwanami/emacs-ctable"))
>   (package! deferred :recipe (:host github :repo "kiwanami/emacs-deferred"))
>   (package! epc :recipe (:host github :repo "kiwanami/emacs-epc")))
> ```

这些依赖很早之前就已经不需要了，可以删掉

**Comment by quarkquartet** [comment]
谢谢回复。
我把多余的依赖包删了，然后把package.el里面的也去了。另外git clone eaf到本地，写如下代码到doom的config.el:
```emacs-lisp
(use-package! eaf
  :load-path "~/.doom.d/emacs-application-framework/"
  :commands (eaf-open)
  :config
  (require 'eaf-pdf-viewer)
  (require 'eaf-markdown-previewer)
  (setq eaf-pdf-dark-mode nil))
```
还是不行。*eaf*里报错内容都一样的。

**Comment by quarkquartet** [comment]
补充：
我尝试了不用python virtualenv,而是回到系统默认的状态，然后把--user加回去。这样就能用了。
不知道有没有virtualenv下的解决方案？

**Comment by manateelazycat** [comment]
> 补充： 我尝试了不用python virtualenv,而是回到系统默认的状态，然后把--user加回去。这样就能用了。 不知道有没有virtualenv下的解决方案？

https://github.com/emacs-eaf/emacs-application-framework/wiki/Python-Virtual-Environment

**Comment by quarkquartet** [comment]
解决。谢谢。
