### ISSUE TITLE
python crashed after switching to pyqt6 on macos m1max

### ISSUE THREAD

**Issue by ror-ian** [emacs-eaf/emacs-application-framework#941]
**Describe the bug**
I switched to pyqt6 and pyqt6-webengine on a mbp m1max laptop. I didn't use "arch -x86_64" to install any of the dependencies since pyqt6 has supported arm64. The installation was completed quite smoothly. Also Emacs and python were started without any issue or warning. But when I use M-x eaf-open-file-manager, qt-webengine could not start and sometimes followed by a crash of python.

**To Reproduce**
1. git pull the latest EAF
2. ./install-eaf.py
3. Start Emacs
4. M-x eaf-open-file-manager

**Expected behavior**
Start eaf file manager correctly.

**Versions (please complete the following info):**
 - OS: macOS Monterey 12.3 (m1max)
 - Versions of Dependencies:
 	- tried python 3.8 and 3.10
	- python-pyqt6-6.2.4
	- python-pyqt6_sip-13.2.1
	- python-pyqt6_webengine-6.2.1
 - M-x emacs-version: GNU Emacs 27.2 (build 1, arm-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559)) 

**Error logs**
qt.webenginecontext: 

GLImplementation: core_profile
Surface Type: OpenGL
Surface Profile: CoreProfile
Surface Version: 4.1
Using Default SG Backend: yes
Using Software Dynamic GL: no
Using Angle: no

Init Parameters:
  *  application-name Python 
  *  browser-subprocess-path /Users/username/Library/Python/3.10/lib/python/site-packages/PyQt6/Qt6/lib/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess 
  *  disable-features DnsOverHttpsUpgrade,ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-speech-api  
  *  disable-web-security  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-gpu-rasterization  
  *  enable-native-gpu-memory-buffers  
  *  enable-threaded-compositing  
  *  ignore-gpu-blocklist  
  *  in-process-gpu  
  *  use-gl core_profile 

Traceback (most recent call last):
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 153, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 172, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/app/file-manager/buffer.py", line 45, in __init__
    BrowserBuffer.__init__(self, buffer_id, url, arguments, False)
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/core/webengine.py", line 768, in __init__
    self.add_widget(BrowserView(buffer_id))
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/core/webengine.py", line 87, in __init__
    self.scroll_step) = get_emacs_vars(
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 335, in get_emacs_vars
    return list(map(lambda result: convert_emacs_bool(result[0], result[1]) if result != [] else False, epc_client.call_sync("get-emacs-vars", args)))
  File "/Users/username/Library/Python/3.10/lib/python/site-packages/epc/handler.py", line 402, in call_sync
    return self._blocking_request(self.call, timeout, name, args)
  File "/Users/username/Library/Python/3.10/lib/python/site-packages/epc/handler.py", line 384, in _blocking_request
    return bc.result(timeout=timeout)
  File "/Users/username/Library/Python/3.10/lib/python/site-packages/epc/handler.py", line 116, in result
    raise reply
epc.handler.ReturnError: [Symbol('void-variable'), Symbol('eaf-browser-default-zoom')]
Traceback (most recent call last):
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 237, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '55fd-bf8b-9859-c44c-fa12-9589-8f88'
Traceback (most recent call last):
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 237, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '55fd-bf8b-9859-c44c-fa12-9589-8f88'
Traceback (most recent call last):
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 237, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '55fd-bf8b-9859-c44c-fa12-9589-8f88'
Traceback (most recent call last):
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 237, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '55fd-bf8b-9859-c44c-fa12-9589-8f88'
Traceback (most recent call last):
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 237, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '55fd-bf8b-9859-c44c-fa12-9589-8f88'
Traceback (most recent call last):
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 237, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '55fd-bf8b-9859-c44c-fa12-9589-8f88'
Traceback (most recent call last):
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/username/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 237, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '55fd-bf8b-9859-c44c-fa12-9589-8f88'

**Additional context**
Sometimes python crashed with following report:
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Python [11824]
Path:                  /Library/Frameworks/Python.framework/Versions/3.10/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.10.4 (3.10.4)
Code Type:             ARM-64 (Native)
Parent Process:        Emacs-arm64-12 [11598]
User ID:               501

Date/Time:             2022-03-30 10:34:40.1755 +0800
OS Version:            macOS 12.3 (21E230)
Report Version:        12
Anonymous UUID:        6161E773-8462-E41D-DEBD-E41C45A3A6FD
Sleep/Wake UUID:       11172ACB-F93E-488E-8B88-C704A6F177F7

Time Awake Since Boot: 300000 seconds
Time Since Wake:       7365 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000010364624c58
Exception Codes:       0x0000000000000001, 0x0000010364624c58
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [11824]

VM Region Info: 0x10364624c58 is not in any region.  Bytes after previous region: 633044356185  Bytes before following region: 104439035573160
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)
--->  GAP OF 0x5f9000000000 BYTES

**Comment by manateelazycat** [comment]
@ror-ian From your error ```epc.handler.ReturnError: [Symbol('void-variable'), Symbol('eaf-browser-default-zoom')]``` , you need add ```(require 'eaf-browser)``` in your config.
