### ISSUE TITLE
macos: epc.handler.ReturnError: [Symbol('void-variable'), Symbol('eaf-browser-default-zoom')]

### ISSUE THREAD

**Issue by zy9306** [emacs-eaf/emacs-application-framework#942]
BTW，eaf-demo is OK

systeminfo:
macOS: 10.15.1 (19B88)

python pkgs:
```
Package             Version
------------------- ---------
appnope             0.1.2
backcall            0.2.0
decorator           5.1.0
epc                 0.0.5
ipython             7.30.1
jedi                0.18.1
lxml                4.8.0
mac-app-frontmost   2020.12.3
matplotlib-inline   0.1.3
parso               0.8.3
pexpect             4.8.0
pickleshare         0.7.5
pip                 22.0.4
prompt-toolkit      3.0.23
ptyprocess          0.7.0
Pygments            2.10.0
pypinyin            0.46.0
PyQt6               6.2.3
PyQt6-Qt6           6.2.4
PyQt6-sip           13.2.1
PyQt6-WebEngine     6.2.1
PyQt6-WebEngine-Qt6 6.2.4
setuptools          61.0.0
sexpdata            0.0.3
traitlets           5.1.1
wcwidth             0.2.5
wheel               0.37.1
```

emacs version:
GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2020-11-22

error log:
```
GLImplementation: core_profile
Surface Type: OpenGL
Surface Profile: CoreProfile
Surface Version: 4.1
Using Default SG Backend: yes
Using Software Dynamic GL: no
Using Angle: no

Init Parameters:
  *  application-name Python 
  *  browser-subprocess-path /Users/zy/Envs/venv38-eaf/lib/python3.8/site-packages/PyQt6/Qt6/lib/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess 
  *  disable-features DnsOverHttpsUpgrade,ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-speech-api  
  *  disable-web-security  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-gpu-rasterization  
  *  enable-native-gpu-memory-buffers  
  *  enable-threaded-compositing  
  *  ignore-gpu-blocklist  
  *  in-process-gpu  
  *  use-gl core_profile 

Traceback (most recent call last):
  File "/Users/zy/projects/my/emacs-application-framework/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/zy/projects/my/emacs-application-framework/eaf.py", line 153, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/Users/zy/projects/my/emacs-application-framework/eaf.py", line 172, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
  File "/Users/zy/projects/my/emacs-application-framework/app/terminal/buffer.py", line 32, in __init__
    BrowserBuffer.__init__(self, buffer_id, url, arguments, False)
  File "/Users/zy/projects/my/emacs-application-framework/core/webengine.py", line 768, in __init__
    self.add_widget(BrowserView(buffer_id))
  File "/Users/zy/projects/my/emacs-application-framework/core/webengine.py", line 87, in __init__
    self.scroll_step) = get_emacs_vars(
  File "/Users/zy/projects/my/emacs-application-framework/core/utils.py", line 335, in get_emacs_vars
    return list(map(lambda result: convert_emacs_bool(result[0], result[1]) if result != [] else False, epc_client.call_sync("get-emacs-vars", args)))
  File "/Users/zy/Envs/venv38-eaf/lib/python3.8/site-packages/epc/handler.py", line 402, in call_sync
    return self._blocking_request(self.call, timeout, name, args)
  File "/Users/zy/Envs/venv38-eaf/lib/python3.8/site-packages/epc/handler.py", line 384, in _blocking_request
    return bc.result(timeout=timeout)
  File "/Users/zy/Envs/venv38-eaf/lib/python3.8/site-packages/epc/handler.py", line 116, in result
    raise reply
epc.handler.ReturnError: [Symbol('void-variable'), Symbol('eaf-browser-default-zoom')]
Traceback (most recent call last):
  File "/Users/zy/projects/my/emacs-application-framework/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/zy/projects/my/emacs-application-framework/eaf.py", line 237, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '7f6f-340d-23b1-a9f2-d51e-a106-f9f0'
Traceback (most recent call last):
  File "/Users/zy/projects/my/emacs-application-framework/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/zy/projects/my/emacs-application-framework/eaf.py", line 237, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '7f6f-340d-23b1-a9f2-d51e-a106-f9f0'

```

**Comment by manateelazycat** [comment]
Add ```(require 'eaf-browser)``` in your config.
