### ISSUE TITLE
Installation fails with `list.remove(x): x not in list`

### ISSUE THREAD

**Issue by leoc** [emacs-eaf/emacs-application-framework#949]
**Describe the bug**

Installation fails when checking GPG keys. Missing other dependency?

I do not use KDE Wallet. Can I use EAF without kdewallet?

**To Reproduce**

1. Update to master
2. Run `./install-eaf.py`

**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM: Archlinux
 - Versions of Dependencies: See below
 - M-x emacs-version: 28.0.50

**Error logs**

Terminal:

```
./install-eaf.py
[EAF] Running yay -Sy --noconfirm --needed @ /home/arthur/.ihsec/leoc/vendor/emacs-application-framework
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
[EAF] ------------------------------------------
[EAF] Installing core dependencies
[EAF] Running yay -Sy --noconfirm --needed wmctrl python-pyqt6 python-pyqt6-webengine python-pyqt6-sip @ /home/arthur/.ihsec/leoc/vendor/emacs-application-framework
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
warning: wmctrl-1.07-6 is up to date -- skipping
warning: python-pyqt6-6.2.3-1 is up to date -- skipping
warning: python-pyqt6-webengine-6.2.1-3 is up to date -- skipping
warning: python-pyqt6-sip-13.2.1-1 is up to date -- skipping
 there is nothing to do
[EAF] Running pip install --user -U epc lxml @ /home/arthur/.ihsec/leoc/vendor/emacs-application-framework
 aRequirement already satisfied: epc in /home/arthur/.local/lib/python3.10/site-packages (0.0.5)
aWARNING: Keyring is skipped due to an exception: Failed to open keyring: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken..
Collecting epc
  Using cached epc-0.0.5-py3-none-any.whl
  Using cached epc-0.0.4.tar.gz (17 kB)
Requirement already satisfied: lxml in /home/arthur/.local/lib/python3.10/site-packages (4.8.0)
Collecting lxml
  Using cached lxml-4.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.0 MB)
  Using cached lxml-4.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.9 MB)
Requirement already satisfied: sexpdata>=0.0.3 in /home/arthur/.local/lib/python3.10/site-packages (from epc) (0.0.3)
[EAF] Finished installing core dependencies
[EAF] ------------------------------------------
[EAF] ------------------------------------------
[EAF] Installing application dependencies
Traceback (most recent call last):
  File "/home/arthur/.ihsec/leoc/vendor/emacs-application-framework/./install-eaf.py", line 465, in <module>
    main()
  File "/home/arthur/.ihsec/leoc/vendor/emacs-application-framework/./install-eaf.py", line 452, in main
    install_app_deps(distro, deps_dict)
  File "/home/arthur/.ihsec/leoc/vendor/emacs-application-framework/./install-eaf.py", line 355, in install_app_deps
    apps_installed = get_installed_apps(app_dir)
  File "/home/arthur/.ihsec/leoc/vendor/emacs-application-framework/./install-eaf.py", line 302, in get_installed_apps
    apps_installed.remove(app)
ValueError: list.remove(x): x not in list

```

**Screenshots**

![2022-04-14-102638_2214x464_scrot](https://user-images.githubusercontent.com/184696/163345888-da93e42e-c4bc-47bc-8c45-3bd5157e7214.png)

**Comment by leoc** [comment]
Okay, I managed to remove the kdewallet that was created long ago with a GPG key that does not exist anymore and created a new kdewallet with the new GPG key.

Now I still only have:

```
[EAF] Finished installing core dependencies
[EAF] ------------------------------------------
[EAF] ------------------------------------------
[EAF] Installing application dependencies
Traceback (most recent call last):
  File "/home/arthur/.ihsec/leoc/vendor/emacs-application-framework/./install-eaf.py", line 465, in <module>
    main()
  File "/home/arthur/.ihsec/leoc/vendor/emacs-application-framework/./install-eaf.py", line 452, in main
    install_app_deps(distro, deps_dict)
  File "/home/arthur/.ihsec/leoc/vendor/emacs-application-framework/./install-eaf.py", line 355, in install_app_deps
    apps_installed = get_installed_apps(app_dir)
  File "/home/arthur/.ihsec/leoc/vendor/emacs-application-framework/./install-eaf.py", line 302, in get_installed_apps
    apps_installed.remove(app)
ValueError: list.remove(x): x not in list
```

**Comment by leoc** [comment]
I completely removed the directory and reinstalled from a freshly cloned repo. Seems to work now.
