### ISSUE TITLE
eaf 升级到 pyqt6 后经常在一些特殊按键后直接崩溃

### ISSUE THREAD

**Issue by C1tas** [emacs-eaf/emacs-application-framework#956]
**Describe the bug**

eaf with pyqt6 always crash after some key press
eaf 升级到 pyqt6 后经常在一些特殊按键后直接崩溃

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.

with total delete python folder /usr/lib/python3.10 /usr/lib/qt6

```
M-x eaf-open-browser
(press esc) or (press enter) (esc或回车) crash
```

```
eaf-open-git 
use jklm move cursor works well
(press arrow-up) (方向键上键) crash
```
**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM:
 - Versions of Dependencies:
 - M-x emacs-version:

系统： arch
WM：  dwm
Linux 5.15.34-1-lts #1 SMP Thu, 14 Apr 2022 05:08:35 +0000 x86_64 GNU/Linux
emacs
GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-19

eaf 版本
```
commit d2f9ddbfacc817de27cc220f462865ae32040eb7 (HEAD -> master, origin/master, origin/HEAD)
Author: edmonfrank <EdmondFrank@hotmail.com>
Date:   Mon Apr 18 22:49:16 2022 +0800

    Fix issue #954. (#955)
```

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffd6629640 (LWP 254987)]
[New Thread 0x7fffc94f9640 (LWP 254988)]
[New Thread 0x7fffc8b69640 (LWP 254989)]
[New Thread 0x7fffbbfff640 (LWP 254990)]
[New Thread 0x7fffc3fff640 (LWP 254991)]
[New Thread 0x7fffc366f640 (LWP 254992)]
[New Thread 0x7fffc2cdf640 (LWP 254993)]
[New Thread 0x7fffc234f640 (LWP 254994)]
[New Thread 0x7fffc19bf640 (LWP 254996)]
[New Thread 0x7fffc102f640 (LWP 254997)]
[New Thread 0x7fffbb66f640 (LWP 254998)]
[New Thread 0x7fffbacdf640 (LWP 254999)]
[Thread 0x7fffbacdf640 (LWP 254999) exited]
[New Thread 0x7fffbacdf640 (LWP 255000)]
[New Thread 0x7fffba34f640 (LWP 255001)]
[New Thread 0x7fffb99bf640 (LWP 255002)]
[Thread 0x7fffb99bf640 (LWP 255002) exited]
[New Thread 0x7fffb99bf640 (LWP 255003)]
[Thread 0x7fffb99bf640 (LWP 255003) exited]
[New Thread 0x7fffb99bf640 (LWP 255004)]
[Thread 0x7fffb99bf640 (LWP 255004) exited]
[New Thread 0x7fffb99bf640 (LWP 255005)]
[New Thread 0x7fffb902f640 (LWP 255006)]
[Thread 0x7fffb902f640 (LWP 255006) exited]
[New Thread 0x7fffb902f640 (LWP 255009)]
[Thread 0x7fffb902f640 (LWP 255009) exited]
[New Thread 0x7fffb902f640 (LWP 255010)]
[Thread 0x7fffb902f640 (LWP 255010) exited]
[New Thread 0x7fffb902f640 (LWP 255011)]
[Thread 0x7fffb902f640 (LWP 255011) exited]
[New Thread 0x7fffb902f640 (LWP 255012)]
qt.webenginecontext: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name eaf.py 
  *  browser-subprocess-path /usr/lib/qt6/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  disable-web-security  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-gpu-rasterization  
  *  enable-native-gpu-memory-buffers  
  *  enable-threaded-compositing  
  *  ignore-gpu-blocklist  
  *  in-process-gpu  
  *  use-gl desktop 

[Thread 0x7fffb902f640 (LWP 255012) exited]
[New Thread 0x7fffb902f640 (LWP 255013)]
[Detaching after fork from child process 255014]
[Detaching after fork from child process 255015]
[Detaching after fork from child process 255016]
[New Thread 0x7fff83fff640 (LWP 255019)]
[New Thread 0x7fff8366f640 (LWP 255020)]
[New Thread 0x7fff82cdf640 (LWP 255021)]
[New Thread 0x7fff8234f640 (LWP 255022)]
[New Thread 0x7fff819bf640 (LWP 255023)]
[New Thread 0x7fff8102f640 (LWP 255024)]
[New Thread 0x7fff6766f640 (LWP 255026)]
[New Thread 0x7fff67fff640 (LWP 255025)]
[New Thread 0x7fff6634f640 (LWP 255027)]
[New Thread 0x7fff659bf640 (LWP 255029)]
[New Thread 0x7fff66cdf640 (LWP 255028)]
[New Thread 0x7fff6502f640 (LWP 255030)]
[New Thread 0x7fff4ffff640 (LWP 255031)]
[New Thread 0x7fff4f66f640 (LWP 255032)]
[New Thread 0x7fff4ecdf640 (LWP 255033)]
[Thread 0x7fff4ecdf640 (LWP 255033) exited]
[New Thread 0x7fff4ecdf640 (LWP 255034)]
[Thread 0x7fff4ecdf640 (LWP 255034) exited]
[New Thread 0x7fff4ecdf640 (LWP 255035)]
[New Thread 0x7fff4e34f640 (LWP 255036)]
[New Thread 0x7fff4d9bf640 (LWP 255037)]
[Thread 0x7fff4d9bf640 (LWP 255037) exited]
[New Thread 0x7fff4d9bf640 (LWP 255038)]
[Thread 0x7fff4d9bf640 (LWP 255038) exited]
[New Thread 0x7fff4d9bf640 (LWP 255039)]
[Thread 0x7fff4d9bf640 (LWP 255039) exited]
[New Thread 0x7fff4d9bf640 (LWP 255040)]
[New Thread 0x7fff37fff640 (LWP 255041)]
[New Thread 0x7fff3766f640 (LWP 255042)]
[New Thread 0x7fff36cdf640 (LWP 255044)]
[Thread 0x7fff36cdf640 (LWP 255044) exited]
[New Thread 0x7fff36cdf640 (LWP 255050)]
[New Thread 0x7fff34f4f640 (LWP 255058)]
[Thread 0x7fff34f4f640 (LWP 255058) exited]
[New Thread 0x7fff34f4f640 (LWP 255059)]
[Thread 0x7fff34f4f640 (LWP 255059) exited]
[New Thread 0x7fff34f4f640 (LWP 255060)]
[Thread 0x7fff34f4f640 (LWP 255060) exited]
[New Thread 0x7fff34f4f640 (LWP 255062)]
[New Thread 0x7fff22fbf640 (LWP 255063)]
[New Thread 0x7fff2262f640 (LWP 255064)]
[New Thread 0x7fff2189f640 (LWP 255065)]
[New Thread 0x7fff0ffff640 (LWP 255066)]
[Thread 0x7fff0ffff640 (LWP 255066) exited]
[New Thread 0x7fff0ffff640 (LWP 255067)]
[Thread 0x7fff0ffff640 (LWP 255067) exited]
[New Thread 0x7fff0ffff640 (LWP 255068)]
[Thread 0x7fff0ffff640 (LWP 255068) exited]
[New Thread 0x7fff0ffff640 (LWP 255069)]
[Detaching after vfork from child process 255070]
[New Thread 0x7fff0f66f640 (LWP 255071)]
[New Thread 0x7fff0cfa7640 (LWP 255074)]
[Thread 0x7fff0ffff640 (LWP 255069) exited]
[New Thread 0x7fff0ffff640 (LWP 255075)]
[New Thread 0x7fff0ffff640 (LWP 255076)]
[Thread 0x7fff0ffff640 (LWP 255075) exited]
[New Thread 0x7ffefffff640 (LWP 255077)]
[Thread 0x7fff0cfa7640 (LWP 255074) exited]
[Thread 0x7ffefffff640 (LWP 255077) exited]
[Thread 0x7fff0ffff640 (LWP 255076) exited]
[Thread 0x7fff0f66f640 (LWP 255071) exited]
[New Thread 0x7fff0f66f640 (LWP 255225)]
[Thread 0x7fff0f66f640 (LWP 255225) exited]
[New Thread 0x7fff0f66f640 (LWP 255229)]
[Thread 0x7fff0f66f640 (LWP 255229) exited]
[New Thread 0x7fff0f66f640 (LWP 255230)]
[Thread 0x7fff0f66f640 (LWP 255230) exited]
[New Thread 0x7fff0f66f640 (LWP 255235)]
[Thread 0x7fff0f66f640 (LWP 255235) exited]
[New Thread 0x7fff0f66f640 (LWP 255295)]
[Thread 0x7fff0f66f640 (LWP 255295) exited]
[New Thread 0x7fff0f66f640 (LWP 255299)]
[Thread 0x7fff0f66f640 (LWP 255299) exited]
[New Thread 0x7fff0f66f640 (LWP 255300)]
[Thread 0x7fff0f66f640 (LWP 255300) exited]
[New Thread 0x7fff0f66f640 (LWP 255302)]
[Thread 0x7fff0f66f640 (LWP 255302) exited]
[New Thread 0x7fff0f66f640 (LWP 255305)]
[Thread 0x7fff0f66f640 (LWP 255305) exited]
[New Thread 0x7fff0f66f640 (LWP 255306)]
[Thread 0x7fff0f66f640 (LWP 255306) exited]
[New Thread 0x7fff0f66f640 (LWP 255307)]
[Thread 0x7fff0f66f640 (LWP 255307) exited]
[New Thread 0x7fff0f66f640 (LWP 255308)]
[Thread 0x7fff0f66f640 (LWP 255308) exited]
[New Thread 0x7fff0f66f640 (LWP 255309)]
[Thread 0x7fff0f66f640 (LWP 255309) exited]
[New Thread 0x7fff0f66f640 (LWP 255311)]
[Thread 0x7fff0f66f640 (LWP 255311) exited]
[New Thread 0x7fff0f66f640 (LWP 255312)]
[Thread 0x7fff0f66f640 (LWP 255312) exited]
[New Thread 0x7fff0f66f640 (LWP 255313)]
[Thread 0x7fff0f66f640 (LWP 255313) exited]
[New Thread 0x7fff0f66f640 (LWP 255319)]
[Thread 0x7fff0f66f640 (LWP 255319) exited]
[New Thread 0x7fff0f66f640 (LWP 255323)]
[Thread 0x7fff0f66f640 (LWP 255323) exited]
[New Thread 0x7fff0f66f640 (LWP 255331)]
[Thread 0x7fff0f66f640 (LWP 255331) exited]
[New Thread 0x7fff0f66f640 (LWP 255332)]
[Thread 0x7fff0f66f640 (LWP 255332) exited]
[New Thread 0x7fff0f66f640 (LWP 255389)]
[Thread 0x7fff0f66f640 (LWP 255389) exited]
[New Thread 0x7fff0f66f640 (LWP 255391)]
[Thread 0x7fff0f66f640 (LWP 255391) exited]
[New Thread 0x7fff0f66f640 (LWP 255395)]
[Thread 0x7fff0f66f640 (LWP 255395) exited]
[New Thread 0x7fff0f66f640 (LWP 255397)]
[Thread 0x7fff0f66f640 (LWP 255397) exited]
[New Thread 0x7fff0f66f640 (LWP 255401)]
[Thread 0x7fff0f66f640 (LWP 255401) exited]
[New Thread 0x7fff0f66f640 (LWP 255460)]
[Thread 0x7fff0f66f640 (LWP 255460) exited]

Thread 1 "python3" received signal SIGTRAP, Trace/breakpoint trap.
0x00007fffedbe2629 in ?? () from /usr/lib/libQt6WebEngineCore.so.6
#0  0x00007fffedbe2629 in  () at /usr/lib/libQt6WebEngineCore.so.6
#1  0x00007fff48af0fe8 in  ()
#2  0x00000000000000f0 in  ()
#3  0x00007fffffffc490 in  ()
#4  0x00005555561b5de8 in  ()
#5  0x00007fffffffc390 in  ()
#6  0x00007fffeda5eb52 in  () at /usr/lib/libQt6WebEngineCore.so.6
#7  0x00007fffffffc340 in  ()
#8  0x00007fffffffc3e0 in  ()
#9  0x00000000000000e0 in  ()
#10 0x070b945cadb32800 in  ()
#11 0x0000555555fe4df0 in  ()
#12 0xffffffffffffff80 in  ()
#13 0x0000000000000000 in  ()

Process *eaf* finished

```

**Additional context**

已经多次尝试删除 /usr/lib/python3.10 /usr/lib/qt6
系统 arch
Linux 5.15.34-1-lts #1 SMP Thu, 14 Apr 2022 05:08:35 +0000 x86_64 GNU/Linux
emacs
GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-19

eaf 版本
```
commit d2f9ddbfacc817de27cc220f462865ae32040eb7 (HEAD -> master, origin/master, origin/HEAD)
Author: edmonfrank <EdmondFrank@hotmail.com>
Date:   Mon Apr 18 22:49:16 2022 +0800

    Fix issue #954. (#955)
```

**Comment by manateelazycat** [comment]
最新版已经修复了
