### ISSUE TITLE
能不能出个使用qt5的版本for win7

### ISSUE THREAD

**Issue by lynnux** [emacs-eaf/emacs-application-framework#972]
Pyqt6不支持win7，而pyqt5可以，所以能不能考虑下做个选项支持pyqt5？

**Comment by EdmondFrank** [comment]
> Pyqt6不支持win7，而pyqt5可以，所以能不可以考虑使用qt-legacy分支

能考虑下做个选项支持pyqt5？

https://github.com/emacs-eaf/emacs-application-framework/tree/qt5-legacy

**Comment by lynnux** [comment]
@EdmondFrank 好的。不过我在一台win10机子上，安装，用的以下命令：
```
git clone depth=1 -b qt5-legacy https://gitee.com/emacs-eaf/emacs-application-framework.git
cd emacs-application-framework
install-eaf.py --use-mirror
```
然后只安装了browser应用。
emacs里启动报错，查看\*eaf\*:
```
Traceback (most recent call last):
  File "c:\green\emacs\emacs-application-framework\core\utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "c:\green\emacs\emacs-application-framework\eaf.py", line 235, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '865e-0bf6-879c-e90b-3be3-a4dc-69a6'

Process *eaf* exited abnormally with code 9
```

**Comment by lynnux** [comment]
貌似找到问题了：
![image](https://user-images.githubusercontent.com/367894/167250272-f7ead7d1-a133-49d4-8dd4-fff0770f89b1.png)
手动开个python窗口，输入`import importlib    dir(importlib.util)` 提示`AttributeError: module 'importlib' has no attribute 'util'`，我装的是Python 3.10.4

**Comment by manateelazycat** [comment]
> @EdmondFrank 好的。不过我在一台win10机子上，安装，用的以下命令：
> 
> ```
> git clone --depth=1 -b qt5-legacy https://gitee.com/emacs-eaf/emacs-application-framework.git
> cd emacs-application-framework
> install-eaf.py --use-mirror
> ```
> 
> 然后只安装了browser应用。 emacs里启动报错，查看*eaf*:
> 
> ```
> Traceback (most recent call last):
>   File "c:\green\emacs\emacs-application-framework\core\utils.py", line 50, in on_signal_received
>     self._func(obj, *args, **kwargs)
>   File "c:\green\emacs\emacs-application-framework\eaf.py", line 235, in update_views
>     view = View(self.buffer_dict[buffer_id], view_info)
> KeyError: '865e-0bf6-879c-e90b-3be3-a4dc-69a6'
> 
> Process *eaf* exited abnormally with code 9
> ```
> 
> 这跟我手动去reset仓库一样的报错：
> 
> ```
> git clone https://gitee.com/emacs-eaf/emacs-application-framework.git
> 恢复成切换到pyqt6之前的版本：
> git reset --hard 98ebfb9f2bd24950adf2988f59b17a822b69f202
> 进入app目录
> git clone https://gitee.com/emacs-eaf/eaf-browser.git
> 手动更名为browser
> git reset --hard 89e3deea7e32a2e83911ff11e12cc3fc2949d9fb
> npm install
> ```
> 
> 报错也是这个

Qt5 已经有分支了，请用 ./install-eaf.py 安装依赖，你大部分崩溃的问题应该都是依赖包没有装好。

先安装 gdb 以后，请用 ```(setq eaf-enable-debug t)``` 打开调试选项，再看看崩溃到哪里了？（一般就是上面的原因）

建议先用 ./install-eaf.py 跑一遍，可以帮你解决很多问题。

**Comment by lynnux** [comment]
难办啊，在家用的win7，也没法正常用qt5-legacy分支。
windows上gdb不好使啊，网上随便找了个单独的gdb.exe，(setq eaf-enable-debug t)后打开eaf浏览器，eaf buffer提示:
```
c:\green\emacs\.emacs.d\bin\gdb.exe: warning: Couldn't determine a path for the index cache directory.
warning: Can not parse XML library list; XML support was disabled at compile time
[New Thread 3336.0xd30]
[New Thread 3336.0xd38]
[New Thread 3336.0xd34]
[New Thread 3336.0xd3c]
[New Thread 3336.0xd40]
[Thread 3336.0xd3c exited with code 0]
[Thread 3336.0xd34 exited with code 0]
[Thread 3336.0xd38 exited with code 0]
[Thread 3336.0xd40 exited with code 0]
[New Thread 3336.0xd48]
[New Thread 3336.0xd4c]
[New Thread 3336.0xd44]
[New Thread 3336.0xd68]
[Thread 3336.0xd44 exited with code 0]
[Thread 3336.0xd48 exited with code 0]
[Thread 3336.0xd68 exited with code 0]
[Thread 3336.0xd4c exited with code 0]
[New Thread 3336.0xe08]
[New Thread 3336.0xd10]
[New Thread 3336.0xe54]
[New Thread 3336.0xcb0]
[New Thread 3336.0xdb8]
[New Thread 3336.0xdbc]
[New Thread 3336.0xe0c]
[Thread 3336.0xe0c exited with code 0]
[New Thread 3336.0xe10]
[New Thread 3336.0xe40]
[New Thread 3336.0xe44]
[Thread 3336.0xe44 exited with code 0]
[New Thread 3336.0xdc0]
[Thread 3336.0xdc0 exited with code 0]
[New Thread 3336.0xe18]
[Thread 3336.0xe18 exited with code 0]
[New Thread 3336.0xe6c]
[Thread 3336.0xe6c exited with code 0]
[New Thread 3336.0xa40]
[Thread 3336.0xa40 exited with code 0]
[New Thread 3336.0xdc8]
[Thread 3336.0xdc8 exited with code 0]
[New Thread 3336.0xe60]
[Thread 3336.0xe60 exited with code 0]
[New Thread 3336.0x9f8]
[New Thread 3336.0xe04]
[New Thread 3336.0xda0]
[New Thread 3336.0xe48]
[New Thread 3336.0xdb0]
[New Thread 3336.0x568]
[New Thread 3336.0xb90]
[New Thread 3336.0x46c]
[Thread 3336.0x46c exited with code 0]
[New Thread 3336.0x438]
[New Thread 3336.0xe94]
[New Thread 3336.0x4fc]
[New Thread 3336.0xeb8]
[New Thread 3336.0x974]
[New Thread 3336.0x970]
[New Thread 3336.0x938]
[New Thread 3336.0xec8]
[New Thread 3336.0xecc]
[New Thread 3336.0x4ec]
[New Thread 3336.0xf50]
[Thread 3336.0xf50 exited with code 0]
[New Thread 3336.0xf48]
[New Thread 3336.0xf44]
[Thread 3336.0xf44 exited with code 0]
[New Thread 3336.0xf3c]
[Thread 3336.0xf3c exited with code 0]
[New Thread 3336.0xf38]
[Thread 3336.0xf38 exited with code 0]
[New Thread 3336.0xf34]
[New Thread 3336.0xe8c]
[New Thread 3336.0x924]
[New Thread 3336.0xf78]
[New Thread 3336.0x388]
[Thread 3336.0x388 exited with code 0]
[New Thread 3336.0x71c]
[New Thread 3336.0x7b4]
[Thread 3336.0x71c exited with code 0]
[Thread 3336.0x7b4 exited with code 0]
[New Thread 3336.0x610]
[Thread 3336.0x610 exited with code 0]
[New Thread 3336.0x7ac]
[Thread 3336.0x7ac exited with code 0]
[New Thread 3336.0x84c]
[Thread 3336.0x84c exited with code 0]
[New Thread 3336.0x83c]
[Thread 3336.0x83c exited with code 0]
[New Thread 3336.0x8ac]
[Thread 3336.0x8ac exited with code 0]
[New Thread 3336.0x844]
[Thread 3336.0x844 exited with code 0]
[New Thread 3336.0x85c]
[Thread 3336.0x85c exited with code 0]
[New Thread 3336.0x514]
[Thread 3336.0x514 exited with code 0]
[New Thread 3336.0x534]
[New Thread 3336.0x780]
[Thread 3336.0xdb8 exited with code 1073741845]
[Thread 3336.0xd30 exited with code 1073741845]
[Thread 3336.0xdbc exited with code 1073741845]
[Thread 3336.0x938 exited with code 1073741845]
[Thread 3336.0x970 exited with code 1073741845]
[Thread 3336.0xeb8 exited with code 1073741845]
[Thread 3336.0xdb0 exited with code 1073741845]
[Thread 3336.0x4ec exited with code 1073741845]
[Thread 3336.0xe10 exited with code 1073741845]
[Thread 3336.0xe8c exited with code 1073741845]
[Thread 3336.0xd0c exited with code 1073741845]
[Thread 3336.0xe94 exited with code 1073741845]
[Thread 3336.0xecc exited with code 1073741845]
[Thread 3336.0xcb0 exited with code 1073741845]
[Thread 3336.0xf78 exited with code 1073741845]
[Thread 3336.0xec8 exited with code 1073741845]
[Thread 3336.0x974 exited with code 1073741845]
[Thread 3336.0xf48 exited with code 1073741845]
[Thread 3336.0x4fc exited with code 1073741845]
[Thread 3336.0x438 exited with code 1073741845]
[Thread 3336.0xf34 exited with code 1073741845]
[Thread 3336.0x9f8 exited with code 1073741845]
[Thread 3336.0xd10 exited with code 1073741845]
[Thread 3336.0x924 exited with code 1073741845]
[Thread 3336.0x568 exited with code 1073741845]
[Thread 3336.0xe48 exited with code 1073741845]
[Thread 3336.0xe04 exited with code 1073741845]
[Thread 3336.0xe08 exited with code 1073741845]
[Thread 3336.0xda0 exited with code 1073741845]
[Thread 3336.0x780 exited with code 1073741845]
[Thread 3336.0xe54 exited with code 1073741845]
[Thread 3336.0xe40 exited with code 1073741845]
[Thread 3336.0x534 exited with code 1073741845]
[Inferior 1 (process 3336) exited with code 010000000025]
No stack.

Process *eaf* exited abnormally with code 1

```

有没有其它debug方法呢，如打印消息什么的，修改eaf.py添加print打印消息显示不了，但是有时候eaf buffer又能显示py的错误，只要能py打印消息那就好办多了。  eaf.py和 core的py文件，我挨个去运行，那些import都是满足了的(除了import core本身的那些)。

**Comment by lynnux** [comment]
![录像4_转](https://user-images.githubusercontent.com/367894/167259959-9cbb91ce-7ab7-4652-91f4-a6c18e17c21e.gif)

**Comment by EdmondFrank** [comment]
> 

你的eaf-browser 用的也是qt5分支嘛？
https://github.com/emacs-eaf/eaf-browser/tree/qt5-legacy

**Comment by MatthewZMD** [comment]
> > 
> 
> 你的eaf-browser 用的也是qt5分支嘛？
> https://github.com/emacs-eaf/eaf-browser/tree/qt5-legacy

只要eaf转换分支后跑install-eaf.py，都会clone其对应的分支

**Comment by lynnux** [comment]
@EdmondFrank 是qt5分支，applications.json里有:
```
"browser": {
        "name": "EAF Browser",
        "type": "app",
        "branch": "qt5-legacy",
        "url": "https://github.com/emacs-eaf/eaf-browser.git",
        "mirror_url": "https://gitee.com/emacs-eaf/eaf-browser.git"
    },
```
查看browesr里的buffer.py内容也都是qt5的

**Comment by lynnux** [comment]
装了browser video-player pdf-viewer mindmap，有video-player和mindmap能用。
mindmap也是各种问题，我记得以前是双击空白添加新节点？现在点击空白没反应，也就只能点击文字修改下文字。还有就是反复失去emacs窗口焦点，eaf里提示：
```
Process *eaf* exited abnormally with code 21
haha
ERROR:epc:PyGetWindowException('Error code from Windows: 0 - 操作成功完成。')
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\handler.py", line 242, in _handle
    reply = handler(uid, *args)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "c:/green/emacs/emacs-application-framework/eaf.py", line 376, in activate_emacs_win32_window
    w[0].activate()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\pygetwindow\_pygetwindow_win.py", line 246, in activate
    _raiseWithLastError()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 0 - 操作成功完成。
ERROR:epc:PyGetWindowException('Error code from Windows: 0 - 操作成功完成。')
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\handler.py", line 242, in _handle
    reply = handler(uid, *args)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "c:/green/emacs/emacs-application-framework/eaf.py", line 376, in activate_emacs_win32_window
    w[0].activate()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\pygetwindow\_pygetwindow_win.py", line 246, in activate
    _raiseWithLastError()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 0 - 操作成功完成。
ERROR:epc:PyGetWindowException('Error code from Windows: 0 - 操作成功完成。')
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\handler.py", line 242, in _handle
    reply = handler(uid, *args)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "c:/green/emacs/emacs-application-framework/eaf.py", line 376, in activate_emacs_win32_window
    w[0].activate()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\pygetwindow\_pygetwindow_win.py", line 246, in activate
    _raiseWithLastError()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 0 - 操作成功完成。
ERROR:epc:PyGetWindowException('Error code from Windows: 0 - 操作成功完成。')
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\handler.py", line 242, in _handle
    reply = handler(uid, *args)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "c:/green/emacs/emacs-application-framework/eaf.py", line 376, in activate_emacs_win32_window
    w[0].activate()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\pygetwindow\_pygetwindow_win.py", line 246, in activate
    _raiseWithLastError()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 0 - 操作成功完成。
ERROR:epc:PyGetWindowException('Error code from Windows: 0 - 操作成功完成。')
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\handler.py", line 242, in _handle
    reply = handler(uid, *args)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\epc\handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "c:/green/emacs/emacs-application-framework/eaf.py", line 376, in activate_emacs_win32_window
    w[0].activate()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\pygetwindow\_pygetwindow_win.py", line 246, in activate
    _raiseWithLastError()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 0 - 操作成功完成。

```

**Comment by manateelazycat** [comment]
看着像 pygetwindow 在你电脑上不能工作。

**Comment by lynnux** [comment]
pygetwindow貌似能工作，只要不随便切换出emacs就没上面提示。这只是小问题。
browser测试本地文件可以工作，然后一些简单网页可以工作，如https://www.orgroam.com/，但https://baidu.com就不行，eaf buffer提示：`Process *eaf* exited abnormally with code 21`。 
将就能用了，我只需要https://github.com/honmaple/emacs-maple-preview 访问它提示的url预览下html, md,org就可以啦！
不过公司那台win10错误提示不是`Process *eaf* exited abnormally with code 21`，上班时候再看了。
话说这个dark mode是真赞！

**Comment by lynnux** [comment]
还有个问题，C-X 3开两个buffer，右边是browser窗口，当打开treemacs时，browser窗口大小不会自动改变大小。如gif所示:
![录像5_转](https://user-images.githubusercontent.com/367894/167280838-8da76eb6-586a-406c-b1da-045e9f182d73.gif)

**Comment by manateelazycat** [comment]
没有精力支持 Qt5
