### ISSUE TITLE
org-open-file fails for pdf-viewer

### ISSUE THREAD

**Issue by bevsxyz** [emacs-eaf/emacs-application-framework#982]
**Describe the bug**

I tried to open pdf files with `eaf-pdf-viewer` for `org-open-file` by doing the following to replace the default function for pdf.

```elisp
(setcdr (assoc ' "\\.pdf\\'" org-file-apps) 'eaf-open)
```
I get the following error

```elisp
[EAF//home/bevan/projects/org-roam/bibliography/bibtex-pdfs/mizuuchi22_evolut_trans_from_singl_rna.pdf] Buffer id '70fa-f951-bf41-4db2-1fcc-6f23-3938' not exists, rebuild EAF buffer.
```

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.

**Expected behavior**

Open the pdf as normal and not a blank buffer

**Versions (please complete the following info):**
 - Distro and DE/WM: Fedora 35 Gnome
 - Versions of Dependencies:
 - M-x emacs-version:27.2

**Error logs**
Please check the `*eaf*` buffer, if there is any error in it, paste it here.

```python
TypeError: expected str, bytes or os.PathLike object, not list
Traceback (most recent call last):
  File "/home/bevan/.config/emacs/straight/repos/emacs-application-framework/core/utils.py", line 50, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/bevan/.config/emacs/straight/build/eaf/eaf.py", line 153, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/bevan/.config/emacs/straight/build/eaf/eaf.py", line 166, in create_buffer
    spec = importlib.util.spec_from_file_location("AppBuffer", module_path)
  File "<frozen importlib._bootstrap_external>", line 745, in spec_from_file_location
```

**Screenshots**

**Additional context**

**Comment by bevsxyz** [comment]
The issue was solved in https://github.com/jkitchin/org-ref/commit/cbe9e870a5f488cdfc5e6a3b5478845ea8acdcde

Closing the issue.
